sudo: required
language: scala
scala: 2.11.7
jdk: oraclejdk8
services:
  - docker
before_install:
  - docker pull java:8
branches:
  only:
    - master
script:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - sbt test dockerBuildAndPush