elasticsearch:
  image: elasticsearch
  ports:
    - "9200:9200"
    - "9300:9300"

kibana:
  image: kibana
  links:
    - "elasticsearch:elasticsearch"
  ports:
    - "5601:5601"

rabbitmq:
  image: rabbitmq:3-management
  environment:
    - "RABBITMQ_DEFAULT_USER=user"
    - "RABBITMQ_DEFAULT_PASS=password"
  ports:
    - "15672:15672"
    - "5672:5672"

helloworld:
  build: .
  links:
    - "rabbitmq:rabbitmq"

indexer:
  build: logstash/indexer
  links:
    - "rabbitmq:rabbitmq"
    - "elasticsearch:elasticsearch"
  command: logstash -f /config-dir/indexer-pipeline.conf
